version: "2"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx_conf/proxy_headers:/etc/nginx/proxy_headers
    links:
      - app_server_a
      - app_server_b

  app_server_a:
    container_name: app_server_a
    ports:
      - "8001:8001"
    build:
      context: ./app_server
    environment:
      - PORT=8001
      - ENV=A
  app_server_b:
    container_name: app_server_b
    ports:
      - "8002:8002"
    build:
      context: ./app_server
    environment:
      - PORT=8002
      - ENV=B